baseURL = "https://avinashdhillor.github.io/"
languageCode = "en-us"
title = "Avinash's Dev Blog"

theme = "hugo-ficurinia"

author = "Avinash Dhillor"
copyright = "Avinash Dhillor - [Working as Software Developer](#)."

paginate = 5
summaryLength = 30

[params]
    description = "Avinash Dhillor's blog about programming and other cool stuff which i learn on daily basis."
    author = "Avinash Dhillor"
    logo = "/logo.png"
    favicon = "/logo.png"
    faviconIco = "/logo.png"
    appletouch = "/logo.png"
    svgicon = "/logo.png"
    icon512 = "/logo.png"
    imageInArticlePreview = true
    enableShareOnFediverse = false
    enableRelatedArticles = true
    relatedArticlesNum = 2 
    forceRedirect = true
    showRss = false

    umamiScriptUrl = "https://analytics.umami.is/script.js"
    umamiWebsiteId = "54d5bbdf-46fe-4fcb-9d71-bf66310b9483"

    cactusCommentsSiteName = "avinashdhillor.github.io"
    cactusCommentsServerName = "cactus.chat"
    cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"
    

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.icons]]
        identifier = "discord"
        name = "Discord"
        url = "https://discord.com/users/978890710759657512"
        weight = 10
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/AvinashDhillor"
        weight = 20
    [[menu.icons]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/avinashdhillor/"
        weight = 30
    [[menu.icons]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/DhillorAvinash"
        weight = 40
    [[menu.icons]]
        identifier = "email"
        name = "Email"
        url = "mailto:avinashdhillor24@gmail.com"
        weight = 50
